#!/bin/bash

brew tap caskroom/cask

brew cask install "iterm2"
brew cask install "google-chrome"
brew cask install "alfred"
brew cask install "setapp"
brew cask install "1password"
brew cask install "slack"
brew cask install "fantastical"
brew cask install "sketch"
brew cask install "spotify"
brew cask install "docker"
brew cask install "telegram"
brew cask install "whatsapp"
brew cask install "keybase"
brew cask install "fork"
brew cask install "gyazo"
brew cask install "insomnia"